const {_electron:electron,expect} = require('@playwright/test');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
  const instance=await electron.launch({args:[path.join(__dirname,'fixture-main.js')]});
  try {
    const page=await instance.firstWindow();
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await expect(page.locator('#status')).toContainText('Input control is responding');
    await page.locator('#toggle').click();
    await expect(page.locator('#status')).toContainText('Switch to MacBook sent');
    await page.locator('#toggle').click();
    await expect(page.locator('#status')).toContainText('Switch to Windows sent');
    await page.locator('#mac').click();
    await page.locator('#windows').click();
    const commands=await instance.evaluate(()=>global.testCommands);
    expect(commands).toEqual([17,15,17,15]);
    await page.locator('#settings-panel > summary').click();
    await page.locator('#macInput').selectOption('15');
    await page.locator('#save').click();
    await expect(page.locator('#save-status')).toContainText('different inputs');
    await page.locator('#macInput').selectOption('18');
    await page.locator('#save').click();
    await expect(page.locator('#save-status')).toContainText('Saved');
    await expect(page.locator('#mac-port')).toHaveText('HDMI 2');
    const registered=await instance.evaluate(({globalShortcut})=>globalShortcut.isRegistered('Control+Alt+Shift+S') && globalShortcut.isRegistered('Control+Alt+Shift+W'));
    expect(registered).toBe(true);
    await instance.evaluate(()=>{global.testFailure=true;});
    await page.locator('#mac').click();
    await expect(page.locator('#status')).toContainText('rejected');
    await instance.evaluate(()=>{global.testFailure=false;global.testEmpty=true;});
    await page.locator('#refresh').click();
    await expect(page.locator('#status')).toContainText('No monitor found');
    await instance.evaluate(()=>{global.testEmpty=false;});
    await page.locator('#refresh').click();
    await expect(page.locator('#status')).toContainText('responding');
    await page.locator('#settings-panel > summary').click();
    await instance.evaluate(({shell})=>{global.opened=[];shell.openExternal=async url=>{global.opened.push(url);};});
    await page.locator('#sharing-panel > summary').click();
    await page.locator('#deskflow').click();
    await page.locator('#releases').click();
    expect((await instance.evaluate(()=>global.opened)).length).toBe(2);
    await page.locator('#sharing-panel > summary').click();
    await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(420,700));
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
    await page.keyboard.press('Tab');
    await page.locator('#toggle').focus();
    expect(await page.locator('#toggle').evaluate(el=>getComputedStyle(el).outlineStyle)).not.toBe('none');
    await page.locator('#toggle').press('Enter');
    await expect(page.locator('#status')).toContainText('sent');
    await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(620,810));
    fs.mkdirSync(path.join(__dirname,'..','.tmp'),{recursive:true});
    await page.screenshot({path:path.join(__dirname,'..','.tmp','ui-test.png')});
    expect(errors).toEqual([]);
    console.log('PASS: toggle, direct inputs, settings validation/save, shortcut registration, errors, empty state, refresh, links, keyboard activation, narrow layout; no renderer errors.');
  } finally {await instance.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
